previewsEnabled: false
previewsExpireAfterDays: 3
services:
- type: web
  name: passthrough
  branch: master
  env: static
  rootDir: static
  pullRequestPreviewsEnabled: true
  buildCommand: echo "hiya"
  staticPublishPath: ./
- type: web
  pullRequestPreviewsEnabled: true
  name: go-server
  branch: master
  rootDir: server
  env: go
  buildCommand: go build -o app .; echo "hi"
  startCommand: ./app
  buildFilter:
    paths: []
    ignoredPaths: ["server/cmd/**"]
  envVars:
  - key: API_HOST
    fromService:
      name: passthrough
      type: web
      envVarKey: RENDER_EXTERNAL_URL
- type: web
  name: diff-repo-flask
  branch: master
  pullRequestPreviewsEnabled: true
  env: python
  repo: https://github.com/joshi4/flask-hello-world
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  buildFilter:
    ignoredPaths:
    - README.md
