previewsEnabled: true
previewsExpireAfterDays: 3
services:
- type: web
  name: go-server
  rootDir: server
  env: go
  maxShutdownDelaySeconds: -1
  buildCommand: go build -o app .; echo "hi"
  startCommand: ./app
  buildFilter:
    paths:
    - "server/**/*"
    ignoredPaths:
    - "server/cmd/**"
- type: cron
  name: test-cron-preview
  env: python
  rootDir: ./static
  buildCommand: echo "hiya"
  schedule: "0/5 * * * *"
  startCommand: date
  maxShutdownDelaySeconds: 1
  envVars:
  - key: API_HOST
    fromService:
      name: passthrough
      type: web
      envVarKey: API_HOST
